config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/about" => "topics#about"

  resources :profiles
  
  resources :topics  do
    resources :feedbacks, :controller =>"topic_feedbacks"
  
    collection do
      post :bulk_update
    end

    member do
      get :favorite
      get :like
      get :subscribe
    end  

  end

  namespace :admin do
    resources :topics
    resources :users
  end

  resources :firefights
  resources :legislators

  root :to => "topics#index"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	validates_presence_of :name

	belongs_to :user 
	has_many :feedbacks
	belongs_to :category

	has_many :taggings
	has_many :tags, :through => :taggings

  has_many :favoritings
  has_many :favorite_users, :through => :favoritings , :source => :user

  has_many :likings
  has_many :like_users, :through => :likings , :source => :user

  has_many :subscribings
  has_many :Subscribe_users, :through => :subscribings , :source => :user

	delegate :name, :to => :category, :prefix => true, :allow_nil => true
	# delegate :email, :to => :user, :prefix => true, :allow_nil => true

	has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/      

  def feedback_users
  	feedbacks.map{ |fe| fe.user }.uniq
  end
  
	def tag_list
   		self.tags.map{ |t| t.name }.join(",")
  	end

	def tag_list=(str)
	   	arr = str.split(",")

		self.tags = arr.map do |t|
	    tag = Tag.find_by_name(t)
	    unless tag
	  	  tag = Tag.create!( :name => t )
	    end
	      tag
	    end
	end

  def created_at_format
    self.created_at.strftime('%b %d %Y %H:%M')
  end
  

end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController

	#後台登入
	before_action :authenticate_user! 

	#檢查權限
	before_action :check_admin

	layout "admin"

	def index
		@topics = Topic.where(:category => nil)
		@users = User.all

		if params[:id]
  		@topic = Topic.find( params[:id] )
  	end
	end

	def update
		Topic.find(params[:id]).update(topic_params)
		flash[:notice] = "Update Success!"
		redirect_to admin_topics_path		
	end

	protected

	def topic_params
		params.require(:topic).permit(:category_id, :description)
	end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	before_action :authenticate_user!, :except => [:index,:show, :about]

	before_action :set_topic, :only =>[ :update, :destroy]

	def index
		#如果出現 tipic_id 代表針對個案id處理edit
		if params[:topic_id]
		  @topic = Topic.find( params[:topic_id] )
		else
			@topic = Topic.new
		end
 
    if current_user && current_user.admin?
      @q = Topic.ransack(params[:q])
    elsif current_user && !current_user.admin?
      @q = Topic.where("user_id = ? OR status = ?", current_user.id , "published").ransack(params[:q])
    else  
      @q = Topic.where(:status => "published").ransack(params[:q])      
    end

    @q.sorts = 'created_at DESC' if @q.sorts.empty?
    @topics = @q.result(distinct: true)
    @topics = @topics.page(params[:page]).per(5) 
    



    #if params[:tag_id]
    #  @topics = Tag.find(params[:tag_id]).topics
    #elsif params[:category]
    #  @topics = @topics.where(:category_id => params[:category])
    #else
    #  @topics = Topic.all
    #end

    #if current_user && current_user.admin?
    #  @topics = @topics.all
    #elsif current_user
    #  @topics = @topics.where("user_id = ? OR status = ?", current_user.id , "published")    
    #else
    #  @topics = @topics.where(:status => "published")
    #end

    #if ["name", "created_at", "feedbacks_count", "latest_feedback_time"].include?( params[:order] )
		#  sort_by = (params[:order]+" DESC")	  		
    #else
    #  sort_by = "id DESC"
    #end

		#@topics = @topics.page(params[:page]).per(5) 
	end

	def new
		@topic = Topic.new
	end

	def create
		@topic = Topic.new(topic_params)
		@topic.user = current_user

		if @topic.save
			redirect_to topics_path
			flash[:notice] = "Create Success"
		elsif 
			@topics = Topic.all
			flash[:alert] = "Create Fail"
			render "index"
		end
	end	

	def show
		@topic = Topic.find(params[:id])

    if current_user && current_user.admin?
      @feedbacks = @topic.feedbacks.all
    elsif current_user
      @feedbacks = @topic.feedbacks.where("user_id = ? OR status =?", current_user.id,"published")
    else
      @feedbacks = @topic.feedbacks.where(:status => "published" )
    end

		@feedback = Feedback.new
	end

	def update
		if params[:destroy_logo] == "1"
      		@topic.logo = nil
	    end

		if @topic.update(topic_params)
			flash[:notice] = "Update Success!"
			redirect_to topics_path
		else 
			@topics = Topic.all
			flash[:alert] = "Update Fail"
			render "index"
		end
	end

	def destroy
		@topic.destroy

		flash[:alert] = "DELETE DONE!"
		redirect_to :back
	end

	def about
		@user = User.all
		@topics =Topic.all
		@feedbacks = Feedback.all
	end

	def bulk_update

		ids =Array(params[:ids])

		topics = ids.map{|i| Topic.find_by_id(i)}.compact
		
		if params[:commit] == "Delete"
			topics.each {|t| t.destroy}
		elsif params[:commit] == "Publish" 
			topics.each {|t| t.update(:status => "published")}
		end

		redirect_to :back
	end

  def favorite

    @topic = Topic.find(params[:id])
    if current_user && !current_user.favorite_topic?(@topic)
      current_user.favorite_topics << @topic    

    elsif current_user && current_user.favorite_topic?(@topic)
      current_user.favorite_topics.delete(@topic) 
    end

    respond_to do |format|
      format.html{ redirect_to :back}
      format.js
    end

  end

  def like
    @topic = Topic.find(params[:id])
    if current_user && !current_user.like_topic?(@topic)
      current_user.like_topics << @topic      
    elsif current_user && current_user.like_topic?(@topic)
      current_user.like_topics.delete(@topic)  
    end

    respond_to do |format|
      format.html{ redirect_to :back}
      format.js
    end
    
  end

  def subscribe
    @topic = Topic.find(params[:id])
    if current_user && !current_user.subscribe_topic?(@topic)
      current_user.subscribe_topics << @topic      
    elsif current_user && current_user.subscribe_topic?(@topic)
      current_user.subscribe_topics.delete(@topic)  
    end

    respond_to do |format|
      format.html{ redirect_to :back}
      format.js
    end


  end

	private

	def topic_params
		params.require(:topic).permit(:name, :content, :category_id, :status, :tag_list, :logo)
	end

	def set_topic
		if current_user.admin? 
			@topic = Topic.find(params[:id])		
		else
			@topic = current_user.topics.find(params[:id])
		end	
	end

end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper

  #Like
  def topic_like_class(topic)
    if current_user && current_user.like_topic?(topic)
      "btn-info"
    else
      "btn-default"
    end    
  end

  def like_word(topic)   
    if current_user && current_user.like_topic?(topic) 
      "取消讚"
    else 
      "按個讚吧"
    end 
  end

  #favorite
  def topic_favorite_class(topic)
    if current_user && current_user.like_topic?(topic)
      "btn-info"
    else
      "btn-default"
    end   
  end

  def favorite_word(topic)   
    if current_user && current_user.like_topic?(topic) 
      "取消收藏"
    else 
      "收藏"
    end 
  end

  #subscribe
  def topic_subscribe_class(topic)
    if current_user && current_user.subscribe_topic?(topic)
      "btn-info"
    else
      "btn-default"
    end   
  end

  def subscribe_word(topic)   
    if current_user && current_user.subscribe_topic?(topic) 
      "取消訂閱"
    else 
      "訂閱"
    end 
  end

end

app/views/topics/_form.html.erb
<div class="form-group">
	<%=t.label :category_id, "Category"%>
	<%=t.select :category_id, Category.all.map{ |x| [x.name, x.id]}, :class => "form-control" %>
</div>

<div class="form-group">
	<%=t.label :status, "Status"%>
	<%=t.select :status,[["Published","published"],["Draft","draft"]], :class => "form-control" %>
</div>

<div class="form-group">
	<%=t.label :name, "Title"%>
	<%=t.text_field :name, :class => "form-control"%>
</div>


<div class="form-group">
	<%= t.label :tag_list %>
	<%= t.select :tag_list, Tag.all.map{ |x| [x.name, x.id]}, {}, :multiple => "true" , :class => "form-control" %>
</div>

<div class="form-group">
	<%=t.label :content, "Content"%>
	<%=t.text_area :content, :class => "form-control"%>
</div>

<div class="form-group">
	<%=t.label :logo, "LOGO"%>
	<%=t.file_field :logo%>
	
	<% if @topic.logo.exists? %>
		<%= link_to image_tag(@topic.logo.url(:thumb)),@topic.logo.url%>
      <%= check_box_tag "destroy_logo", "1" %> 刪除檔案
    <% end %>

</div>

<%= t.submit "送出",:class => "btn btn-primary" %>

<script>
  $("#topic_category_id").select2();
  $("#topic_status").select2();

  $("#topic_tag_list").select2({
     tags: <%=raw Tag.all.map{ |t| t.name }.to_json %>,
     tokenSeparators: [',', ' ']
   });

</script>

app/views/topics/_like.html.erb
  <%= link_to like_topic_path(@topic), :class => "btn #{topic_like_class(@topic)}", :remote => true, :id => "like-btn" do %>
    <span id="like_number"><%= @topic.like_users.size %>人覺得讚</span>
    <span id="like-word"><%= like_word(@topic) %></span>
  <% end %>

<p> 誰也按讚：
  <% @topic.like_users.each do |u|  %>
    <%= link_to u.username, profile_path(u) %>, 
  <% end %>
</p>

app/views/topics/_show.html.erb
<h1>預覽</h1>

<h1>標題：<%= @topic.name %> </h1>
  


<li>
內容：<br>
<%= @topic.content %>
</li> 

</ul>

<% if @topic.logo.exists? %>
  <%= link_to image_tag(@topic.logo.url(:thumb)),@topic.logo.url%>
<%end%>

app/views/topics/about.html.erb
<p>
Topics:<%= @topics.size %> 
</p>
<p>
	Feedbacks: <%= @feedbacks.count %>
</p>

<p>
	Users:<%= @user.count %>
</p>

<%= link_to "Topics Index", topics_path%>

app/views/topics/aboutsite.html.erb
<p>
Topics:<%= @topics.size %> 
</p>
<p>
	Feedbacks: <%= @feedbacks.count %>
</p>

<p>
	Users:<%= @user.count %>
</p>

<%= link_to "Topics Index", topics_path%>

app/views/topics/edit.html.erb
<h1>Edit Page</h1>

<%= form_for @topic, :class =>"form" do |t|%>

<%= render :partial =>"form", :locals => {:t => t} %>
<%=t.submit "Update", :class => "btn btn-primary"%>

<%end%>

<%= link_to "Topics Index", topics_path%>

app/views/topics/favorite.js.erb
$("#favorite-btn").toggleClass('btn-default');
$("#favorite-btn").toggleClass('btn-info');

<% if current_user.favorite_topic?(@topic) %>
  $("#favorite-word").text("取消收藏")
<%else%>
  $("#favorite-word").text("收藏")
<%end%>

app/views/topics/index.html.erb
<%= link_to "About", about_path,:class => "btn btn-default"%>


<table class="table">
	<tr>
		<td>分類列表
			<% Category.all.each do |c|%>
			<%= link_to c.name, topics_path( :category => c.id), :class => "btn btn-primary"%>
			<%end%>
			<%= link_to "All", topics_path,:class => "btn btn-primary" %>
		</td>

	
	</tr>
</table>

<%= search_form_for @q do |f| %>

  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>

  <%= f.label :content_cont %>
  <%= f.search_field :content_cont %>

  <%= f.submit %>
<% end %>

<%=form_tag bulk_update_topics_path do %> <form>

<table class="table">
	<tr>
		<td><%= sort_link(@q, :name, '標題') %></td>
		<td>Category</td>
		<td>Poster</td>
		<td>Tags</td>
		<td><%= sort_link(@q, :created_at, '發表時間') %></td>
		<td><%= sort_link(@q, :feedbacks_count, '回覆數', default_order: :desc) %></td>
		<td>Feedbackers</td>
		<td><%= sort_link(@q, :latest_feedback_time, '最新回覆時間') %></td>
		<td>Control</td>
		<td>Status</td>
	</tr>

	<% @topics.each do |t| %>
		
		<tr >
		
			<td>
			<%= check_box_tag "ids[]", t.id, false %>
			<%= link_to t.name, topic_path(t)%>
				
			</td>
			<td>
				<%= t.category_name%>
			</td>
			<td>
				<%= link_to profile_path(:id => t.user.username) do%>
					<%= image_tag t.user.gravatar_url, :size => "30x30" %>
					<%= t.user.username%>
				<% end %>

			</td>
			<td>
				<% t.tags.each do |t|%>
					<%= link_to t.name, topics_path( :tag_id => t )%>
				<%end%>
			</td>
			<td>
				<%= t.created_at_format  %>
			</td>
			<td>
				<%= t.feedbacks.size %> pieces of feedback
			</td>
			<td>
				<ul>
					<% t.feedback_users.each do |u| %>
						<li><%= link_to u.username, profile_path(:id => u.username) %></li>
					<%end%>
				</ul>
			</td>
			<td><%= t.latest_feedback_time%></td>
			<td>	

			<%# ajax partial 實作%>
					<%= link_to "預覽", topic_path(t),:class => "btn btn-primary" , :remote => true %>

				<% if current_user && ( t.user == current_user || current_user.admin? ) %>
					<%= link_to "Edit", topics_path(:topic_id => t ), :class => "btn btn-default"%>	
				<%# 僅改變url, 取值及更新由下面的form for 執行%>
				
					<%= link_to "Delete", topic_path(t), :method => :delete, :data => {:confirm => "sure?"},:class => "btn btn-danger" %>

				<% end %>
			</td>
			<td><%=t.status%></td>
		</tr>
	<%end%>
</table>
	<%= submit_tag "Delete"%>
	<%= submit_tag "Publish"%>
<%end%>

<%= paginate @topics %>

<div id="show_area"></div>

<hr>
<%#將edit new 放到首頁%>
<%= link_to "新文章", topics_path,:class => "btn btn-primary"%>


<%
  if params[:topic_id]
  	#edit
    url = topic_path(@topic)
  else 
  	#new
    url = topics_path
  end
%>

<%= form_for @topic, :url => url do |t| %>

	<%= render :partial => 'form', :locals => { :t => t} %>

<% end %>

app/views/topics/like.js.erb
$("#like-btn").toggleClass('btn-default');
$("#like-btn").toggleClass('btn-info');

<% if current_user.like_topic?(@topic) %>
  $("#like_number").text("你跟" + <%= @topic.like_users.size %> + "人覺得讚，")
  $("#like-word").text("取消讚")
<%else%>
  $("#like_number").text(<%= @topic.like_users.size %> + "人覺得讚")
  $("#like-word").text("按個讚吧")
<%end%>

app/views/topics/show.html.erb
<h1>
	Title: <%= @topic.name %> 
	
	<%= link_to favorite_topic_path(@topic),:class => "btn #{topic_favorite_class(@topic)}", :id => "favorite-btn", :remote => true do %>
		<span id="favorite-word"><%= favorite_word(@topic) %></span>
	<% end %>

	<%= link_to subscribe_topic_path(@topic),:class => "btn #{topic_subscribe_class(@topic)}", :id => "subscribe-btn", :remote => true do %>
		<span id="subscribe-word"><%= subscribe_word(@topic) %></span>
	<% end %>
</h1>

<div id="fb-root" >
	<div class="container">
	    <script>
	    	(function(d, s, id) {
				  var js, fjs = d.getElementsByTagName(s)[0];
				  if (d.getElementById(id)) return;
				  js = d.createElement(s); js.id = id;
				  js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.4&appId=1473500716238271";
				  fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));
			</script>

			<div class="fb-like"></div>
			
			<script>
				(function(d, s, id) {
				  var js, fjs = d.getElementsByTagName(s)[0];
				  if (d.getElementById(id)) return;
				  js = d.createElement(s); js.id = id;
				  js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.4&appId=141000662921301";
				  fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));
			</script>

			<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count"></div>

	</div>
</div>

<div id="fb-root">
<div class="container">
	
</div>
</div>

<ul>


<li>Category: <%= @topic.category_name %></li>
<li>Author:
	<%= image_tag @topic.user.gravatar_url, :size => "30x30" %>
	<%= link_to @topic.user.username, profile_path(@topic.user)%>
</li>
<li>Status: <%= @topic.status%></li>
<li>Tags: 
	<% @topic.tags.each do |ta|%>
		<%= ta.name %>,
	<%end%>
</li>
<li>Content: <%= @topic.content %></li> 
</ul>


<% if @topic.logo.exists? %>
	<%= link_to image_tag(@topic.logo.url(:thumb)),@topic.logo.url%>
<%end%>

	<%= render :partial => 'like' %>

<h3>Feedbacks</h3>
<table class="table" id="feedbacks-table">
	<thead>
  	<tr>
      <td>Feedbacker</td>
      <td>Content</td>
      <td>Feedback Time</td>
      <td>Control</td>
      <td>Status</td>
    </tr>
  </thead>
  <tbody>
    <% @feedbacks.each do |fe| %>
      <tr id="feedback-<%= fe.id %>">
        <td>
          <%= link_to profile_path(fe.user) do %>
             <%= image_tag fe.user.gravatar_url, :size =>"30x30" %>
             <%= fe.user.username %>
          <% end %>

        </td>
        <td>
          <%= fe.content%>
          <% if fe.logo.exists? %>
            <%= link_to image_tag(fe.logo.url(:thumb)),fe.logo.url%>
          <%end%>
        </td>
        <td><%= fe.created_at%></td>

        <td>
        <% if current_user && ( fe.user == current_user || current_user.admin? ) %>
          <%= link_to "Edit", edit_topic_feedback_path(@topic,fe),:class => "btn btn-default"%>
          <%= link_to "Delete", topic_feedback_path(@topic,fe), :remote => true, :method => :delete, :class => "btn btn-danger"%>
        <% end %>
        </td>
        <td>
          <%= fe.status %>
        </td>
      </tr>
    <%end%>
  </tbody>

</table>

<%= form_for [@topic, @feedback], :class =>"form",:remote => true do |fe|%>
	
	<div class="form-group">
		<%=fe.label :content, "Content"%>
		<%=fe.text_area :content, :class => "form-control", :id => "feedbacks-content-area" %>
	</div>

	<div class="form-group">
	    <%=fe.label :logo, "LOGO"%>
	    <%=fe.file_field :logo,:id => "feedbacks-logo-area"%>
	</div>

	<%=fe.submit "Create", :class => "btn btn-primary"%>

<%end%>



<hr>
<%= link_to "Topics Index", topics_path%>

<%= content_for :head do %>
    <%= tag(:meta, :content => @topic.name, :property => "og:title") %>
    <%= tag(:meta, :content => "article", :property => "og:type") %>
    <%= tag(:meta, :content => topic_url(@topic), :property => "og:url") %>
<% end %>

app/views/topics/show.js.erb
$('#show_area').html("<%= escape_javascript(render :partial => 'show') %>")
             .css({ backgroundColor: '#ffff99' });

app/views/topics/subscribe.js.erb
$("#subscribe-btn").toggleClass('btn-default');
$("#subscribe-btn").toggleClass('btn-info');

<% if current_user.subscribe_topic?(@topic) %>
  $("#subscribe-word").text("取消訂閱")
<%else%>
  $("#subscribe-word").text("訂閱")
<%end%>