config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/about" => "topics#about"

  resources :profiles
  
  resources :topics  do
    resources :feedbacks, :controller =>"topic_feedbacks"
  
    collection do
      post :bulk_update
    end

    member do
      get :favorite
      get :like
      get :subscribe
    end  

  end

  namespace :admin do
    resources :topics
    resources :users
  end

  resources :firefights
  resources :legislators

  root :to => "topics#index"

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1><%= link_to "翻轉立院 Fliply - Admin Page", topics_path%></h1>
			<%if flash[:notice].present? %>
				<div class="alert alert-success" role="alert">
					<%= flash[:notice] %>
				</div>
			<%end%>
			<%if flash[:alert].present? %>
				<div class="alert alert-danger" role="alert">
					<%= flash[:alert] %>
				</div>
			<%end%>

			<% if current_user %>
				Hello! 
        <%= link_to profile_path(:id => current_user.username) do %>
          <%= image_tag current_user.gravatar_url, :size =>"30x30" %>
          <%= current_user.username %> 
        <% end %>
          		<%= link_to'登出', destroy_user_session_path, :method => :delete, :class => "btn btn-default" %> |
          		<%= link_to'修改登入資料', edit_registration_path(:user), :class => "btn btn-default" %>
      		<% else %>
      			<%= link_to "Facebook登入", user_omniauth_authorize_path(:facebook) , :class => "btn btn-default"%> |
          		<%= link_to'註冊', new_registration_path(:user), :class => "btn btn-default" %> |
          		<%= link_to'Email 登入', new_session_path(:user), :class => "btn btn-default" %>
      		<% end %>
      		<%if current_user && current_user.admin?%>
				<%= link_to "ADMIN", admin_topics_path, :class => "btn btn-default" %>
			<% end %>
			<%= link_to "Topics Index", topics_path, :class => "btn btn-default"%>

			<%= yield %>

		</div>

	</div>

</div>






</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1><%= link_to "翻轉立院 Fliply", topics_path %></h1>
			<%if flash[:notice].present? %>
				<div class="alert alert-success" role="alert">
					<%= flash[:notice] %>
				</div>
			<%end%>
			<%if flash[:alert].present? %>
				<div class="alert alert-danger" role="alert">
					<%= flash[:alert] %>
				</div>
			<%end%>
			

			<% if current_user %>
				Hello! 
				<%= link_to profile_path(:id => current_user.username) do %>
          <%= image_tag current_user.gravatar_url, :size =>"30x30" %>
          <%= current_user.username %> 
        <% end %>
          		<%= link_to'登出', destroy_user_session_path, :method => :delete, :class => "btn btn-default" %> |
          		<%= link_to'修改登入資料', edit_registration_path(:user), :class => "btn btn-default" %>
      		<% else %>
      			<%= link_to "Facebook登入", user_omniauth_authorize_path(:facebook), :class => "btn btn-primary" %> |
          		<%= link_to'註冊', new_registration_path(:user), :class => "btn btn-default" %> |
          		<%= link_to'Email 登入', new_session_path(:user), :class => "btn btn-default" %>
      		<% end %>
      		<%if current_user && current_user.admin?%>
				<%= link_to "ADMIN", admin_topics_path,:class => "btn btn-default" %>
			<% end %>
			<%= link_to "首頁", topics_path,:class => "btn btn-default" %>
      <%= link_to "立委列表", legislators_path,:class => "btn btn-default" %>
			<%= yield  %>
			

		</div>

	</div>

</div>


</body>
</html>